Metrics/BlockLength:
  Exclude:
    - 'ontohub-models.gemspec'
    - 'spec/**/*'
    - 'db/migrate/*'

Layout/AlignParameters:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
