sudo: false
dist: trusty

language: ruby
cache: bundler

rvm:
  - 2.5.3

services:
  - postgresql

addons:
  postgresql: '9.6'

notifications:
  email: false

before_install:
  - gem install bundler

before_script:
  - RAILS_ENV=test bin/rails db:recreate

script:
  - bundle exec rspec --format progress
